apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inteli-demo.fullname" . }}-config
  labels:
    {{- include "inteli-demo.labels" . | nindent 4 }}
data:
  applicationConfig.json: {{ .Values.config.applicationConfig | toJson }}