apiVersion: v2
name: inteli-demo
appVersion: '3.0.1'
description: A Helm chart for inteli-demo
version: '3.0.1'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
