# fullNameOverride:
config:
  port: 80
  logLevel: info
  enableLivenessProbe: true
  applicationConfig:
    foo: bar
    blah: reeeee
ingress:
  # annotations: {}
  # className: ""
  paths:
    - /

replicaCount: 1

image:
  repository: ghcr.io/digicatapult/inteli-demo
  pullPolicy: IfNotPresent
  tag: 'v2.0.0'
