# fullNameOverride:
config:
  port: 80
  logLevel: info
  enableLivenessProbe: true
  applicationConfig:
    authDomain: inteli.eu.auth0.com
    clientID: A5PgyCfBMIOhHQEIyImtqLGuD1VJ9VgP
    custAuthClientID: BvJaBbxOce4Pwi5PZpjBTStvNWwzugPd
    t1AuthClientID: 6NfUcA48JdhKXYCc9yGTwM2m1gzcjOTU
    authAudience: inteli-dev
    apiHost: localhost
    apiPort: 3000
    substrateHost: localhost
    substratePort: 9944
    vitalamDemoPersona: cust
ingress:
  # annotations: {}
  # className: ""
  paths:
    - /

replicaCount: 1

image:
  repository: ghcr.io/digicatapult/inteli-demo
  pullPolicy: IfNotPresent
  tag: 'v2.2.2'
