# fullNameOverride:
config:
  port: 80
  logLevel: info
  enableLivenessProbe: true
  applicationConfig: {}
ingress:
  # annotations: {}
  # className: ""
  paths:
    - /

replicaCount: 1

image:
  repository: ghcr.io/digicatapult/inteli-demo
  pullPolicy: IfNotPresent
  tag: 'v2.0.0